Sahil/history
ideahacks/ideahacks.la pull request #384
Opened 2020-09-25 02:17 UTC by sdani1923

Pull request for History Page:
> Updated the colors, styles, formatting, and text to match the new website design on the Figma
> Updated the winners sections with the winners from 2020 Ideahacks
> Sponsors section is still in the drop down format as requested by Robert
> Updated the top of the page with the new history logo as well

2020-09-25 02:18 UTC, sdani1923 commented
Pull request for History Page:
> Updated the colors, styles, formatting, and text to match the new website design on the Figma
> Updated the winners sections with the winners from 2020 Ideahacks
> Sponsors section is still in the drop down format as requested by Robert
> Updated the top of the page with the new history logo as well

2020-09-25 04:09 UTC, robertnperalta requested changes
Looking good! There are a handful of things I'd like you to fix:
* Update the Google Fonts `<link>` in the `<head>`. You can find the new one in the website notes doc
  * Tangentially related, make sure to update the `font-family` of `.history-year .btn` in `history.css` to Roboto
* Don't use an image for the "History" header. Replace that whole `div>img` thing with an `<h1>`. The global styles in `style.css` should handle most of the formatting, and you can make small tweaks to make it look right
* Your way of getting the horizontal lines around the section headers is very creative! There has to be a better way of doing it out there somewhere, but I can't think of it and it works well, so we'll roll with it. Just one thing: the lines are actually slightly visible around the titles just after the page transitions to mobile formatting. To prevent this, add a class to those `<div>`s, move all their styling out of the `style` attribute and into the CSS file. Then add a rule under the last media query (`@media (max-width: 768px)`) that overrides the `border-bottom` style to make it `none`
* The sponsor drawer background colors aren't consistent. Change the default background color to white, and for 2019 and 2017, override that default with some other color that's in-theme. I was thinking the light blue, but if you can think of another color that works better, go for it

I would have commented these directly on the code so you can see exactly which lines I'm talking about, but GitHub displays it weirdly when you didn't directly make changes to the lines I want to comment on. Good job on this page overall! If you have any questions about the changes I requested, let me know

2020-09-25 04:09 UTC, robertnperalta commented on public/css/history.css
> +	/*#dd8064*/
You can delete this commented out color and all the other ones you left behind. If the next person working on this wants to see what they were, they can always look back in the repo history

2020-09-25 04:09 UTC, robertnperalta commented on views/history.hbs
> +                    <p> <b>PRIZE:</b> New Matter 3-D printer<br><br> <b>TEAM:</b> Andrew Chen, Matthew Wong, Robert Zalog, and Christine Chen (not pictured)<br><br> <b>PROJECT:</b>A ‘smart’ Frisbee t
Missing a space after `<b>PROJECT:</b>`. It's fine to do it this way for now, but for future reference, the convention I've seen is putting the space with the first part, not the second (i.e. `<b>TEAM: </b>Andrew` instead of `<b>TEAM:</b> Andrew`). Personally, I find it easier to catch mistakes this way too

2020-09-27 00:07 UTC, sdani1923 commented on public/css/history.css
> +	/*#dd8064*/
Fixed this

2020-09-27 00:07 UTC, sdani1923 commented on views/history.hbs
> +                    <p> <b>PRIZE:</b> New Matter 3-D printer<br><br> <b>TEAM:</b> Andrew Chen, Matthew Wong, Robert Zalog, and Christine Chen (not pictured)<br><br> <b>PROJECT:</b>A ‘smart’ Frisbee t
Fixed!

2020-09-27 02:53 UTC, sdani1923 commented
I've updated the history page as per all the requirements mentioned above. So, I think it should be good to go, please check it out and merge it to the main repo if it looks all good!

2020-09-27 17:01 UTC, robertnperalta approved these changes
Lgtm!

2020-09-27 17:01 UTC, merged