Added a few new views to history page
ideahacks/ideahacks.la pull request #408
Opened 2021-08-11 02:46 UTC by yolanda10202

## Changes made
### HTML
- Added history graphics and logo to the page.
- Changed the grid layout inside the black and white containers.

### CSS
- Added styles for the history graphics and logo.

## Few Questions and Concerns
- Not sure why the tabs of the black and white containers have decreasing sizes.
- Are fonts for the website imported yet?

## Few Notes
- Please add landing graphics to graphics folder.
- Content within the white and black containers are still in progress.
- Since there isn't any content written for IDEA HACKS 2021 yet, I'll just make a copy of 2020's content.

2021-08-11 03:15 UTC, robertnperalta requested changes
Looking good so far! In the future though, try to keep pull requests for finished pages. I can just look at your branch normally if you need help. That said, we can leave this one open; just request my review again when it's fully finished.

To answer your questions:
* I explained the tab issue in the comments below, but essentially it's just a defunct `section-header` class
* I can see why you're asking about fonts being imported, but I think Courtney just forgot to update the fonts on the design to our new fonts. I'll talk to her and get back to you
* The landing graphics/logos for past years are now in the graphics folder

2021-08-11 03:15 UTC, robertnperalta commented on public/css/history.css
> +}
A couple things about this CSS:
* `.wrapper` is actually a global class from `style.css`, so you don't have to worry about `background-color` or `color`; they're already set for you. Just leaving `padding-top` should be enough for this page
* Just as a reminder, make sure you're using the CSS variables that I added in `style.css`. It'll save you time and make everything more consistent

2021-08-11 03:15 UTC, robertnperalta commented on public/css/history.css
>  }
This is the reason the tabs are being positioned weirdly, specifically the `height: 35px;`. This entire rule is actually useless now; you can just get rid of it from here and the HTML

2021-08-11 03:15 UTC, robertnperalta commented on public/css/history.css
>  }
Same thing about CSS variables here and everywhere else in your code

2021-08-11 03:15 UTC, robertnperalta commented on views/history.hbs
> +                </div>
Like I mentioned above, it's the `section-header` class that's messing up this tab and the other ones

2021-08-22 07:04 UTC, robertnperalta requested changes
Looks really good! Just some nitpicky sizing stuff to fix; the boundary between mobile and desktop styling always gets funky, but we want to make sure it still looks good if someone split screens the website or something. Also don't forget about using CSS variables for colors like I mentioned.

2021-08-22 07:04 UTC, robertnperalta commented on public/css/history.css
> +}
Small nitpick: instead of using `margin-left` the property `left` is a little better to use here.

Also, the logo butts up against the edges of the screen and ends up overlapping with the light-colored mountains, making it hard to read. Add some padding on the sides (maybe 20-30ishpx or so) and raise the logo up on small screens so it stays with a green background.

2021-08-22 07:04 UTC, robertnperalta commented on public/css/history.css
> +}
Sorry you had to hack this together; I didn't realize the text wasn't part of the graphic on the Figma. I've updated the logo in the drive to one with the text, so you won't have to worry about this stuff.

2021-08-22 07:04 UTC, robertnperalta commented on public/css/history.css
>  }
Can you bump the font size here to 20px to match the Figma?

2021-08-22 07:04 UTC, robertnperalta commented on views/history.hbs
> +                        </div>
The sponsor logos get uncomfortably small as the screen approaches the mobile styling. It might be worth it to fix each logo width by pixels instead and turn `.sponsors_container` into a flexbox that handles all the complicated wrapping and spacing for you as the screen gets smaller.

2021-08-22 07:04 UTC, robertnperalta commented on views/history.hbs
> +                        </div>
Like the sponsor logos, the team picture gets way too small as the screen shrinks. You could change this to something like `col-sm-6 col-md-4` or maybe fix the image column width and just let the text shrink and wrap as necessary.

In fact, with the font size up to 20px, it feels small even on a full desktop screen. It might be best to have it be a default 5/7 split, then go to 6/6 on smaller screens before mobile styling.

2021-08-22 07:04 UTC, robertnperalta commented on views/history.hbs
> -                    <span class="glyphicon glyphicon-chevron-down"></span>
Since this is gone, I think you can delete `history.js` and the `<script>` that links it to the HTML.

2021-08-22 07:04 UTC, robertnperalta commented on views/history.hbs
> +        </div>
Instead of using this to make sure the tab container wraps properly around the content, you can just add `.clearfix` alongside `.black/white-tab-container`.  This has the added benefit of generating the `::after` pseudo element, which `style.css` sets up to make sure that none of your text gets hidden behind a tab, which it currently does on small screens.

2021-08-23 14:48 UTC, yolanda10202 commented on public/css/history.css
> +}
Okay. I'll put the graphic instead. Thanks!

2021-08-25 02:58 UTC, robertnperalta requested changes
Almost there. Notice that your branch is currently failing the Travis checks. If you go to the "Checks" tab of this PR, you can click through to the build itself and you'll see that your code isn't matching our Prettier standards. You probably have pending changes in your workspace; you can just commit those with the message "Run Prettier" and push them up to get the build passing again.

Just a couple things on top of the comments that I can't comment on the code:
* Bump the font size for the into text to 20px too
* Increase the bottom margin on `.introduction` on small screens to something like 50px so the text doesn't get covered by the tab
* Update the 2021 section with the info from the doc I sent

2021-08-25 02:58 UTC, robertnperalta commented on public/css/history.css
> +	color: #ffffff;
Please swap out your hex codes in all of your CSS for the CSS variables provided from `style.css`. It's more consistent and easier for you in the long run.

2021-08-25 02:58 UTC, robertnperalta commented on public/css/history.css
> +}
On small screens, the logo butts up against the sides of the screen. Add some side padding/margin (30ish px) so this doesn't happen.

2021-08-25 02:58 UTC, robertnperalta commented on public/css/history.css
> +}
Also on small screens, the logo will overlap with the mountains, making it hard to read. Reduce the `top` style for small screens to something like 120px so it overlaps less.

2021-08-26 03:14 UTC, robertnperalta approved these changes
LGTM!

2021-08-26 03:14 UTC, merged