Update "my parts" and "team parts" page to 2021 design
ideahacks/ideahacks.la pull request #420
Opened 2021-11-11 03:59 UTC by RogueArt

Team parts page is good, I have some concerns about the my parts page:
Note: "my parts" is found under /dashboard/me/parts and the team parts page is under /dashboard/parts

## Questions/Concerns:
1. Can someone help me with Bootstrap so the "My Parts" is always below the "Parts Quick Search" or vice versa?
For now, it’s all side by side:
![image](https://user-images.githubusercontent.com/57082175/141234475-31e31fc1-d140-4051-8e86-542061d8a1a2.png)

2. What’s happening that’s making the Name/Category/Quantity part wider than the actual item listings?
![image](https://user-images.githubusercontent.com/57082175/141234496-0e08cf95-4d52-4d0c-b385-9aa5eca3c440.png)

3. Why isn’t the text aligned properly? Like for example, Battery is more to the right than Electromechanical or Miscellaneous?
![image](https://user-images.githubusercontent.com/57082175/141234533-1f510ae8-df4c-40a3-a1f1-30cc54f62113.png)

2022-01-12 23:06 UTC, robertnperalta requested changes
Looks really good! Just a couple more things that need changing that I couldn't put on the code:

* On both pages, the logo overlaps with the mountains in the graphic when the screen gets small, making it unreadable. Doing something like the Team page does, where the top margin decreases as the screen gets smaller, or like the landing page does with a filler bar on top, would help fix the problem quickly
* For the full parts list, the part thumbnails, both in the grid and in the modal, are fixed to 200px wide, which overflows when stuff gets smaller and creates problems on the boundary of desktop and mobile styling. I'd suggest giving them `width: 100%;` and `max-width: 200px`
* Also on the full parts list, the text in the modal is still white, making it unreadable. Should be a quick fix to make it black, but you'll have to make the change in `dashboard-parts-modal.css`
* I see that the My Parts page has leftover dashboard buttons (admin, settings, log out) from two years ago when it used to be the landing page for a user. Just get rid of those since it's no longer the landing page
---
To answer your questions:
1. No longer applies, but removing the Bootstrap column classes (the `col-*-*`) from the divs wrapping each section would have let the divs fill the whole screen and push the parts quick search to the bottom
2. It's wider because the div that wraps that row has the Bootstrap `row` class, which adds negative margins on the left and right. It's intended to be used to wrap their column system so there's no extra padding on the sides of a row, but was misused here in the past (probably by me)
3. The text doesn't align because the text column is extra thin (col-*-2) and text aligned center. The ones that are farther out to the left are overflowing their containers and so are pressed as far left as they can go

2022-01-12 23:06 UTC, robertnperalta commented on views/dashboard-my-parts.hbs
> +                                <div class="part-entry row" data-full={{name}}>
Why remove the double quotes? Without them, it breaks the hover text

2022-01-12 23:06 UTC, robertnperalta commented on views/dashboard-my-parts.hbs
> +                    <hr class='banner-underline'>
I know I told you to leave this in, but after looking at it some more and thinking about it for a while, I think it would be best if we just got rid of it. The actual parts page isn't hard to find and if the user comes to the "My Parts" page, they aren't expecting a full list of all other parts to be there too. Sorry for the 180, but please remove the parts quick search entirely

2022-01-13 03:25 UTC, RogueArt commented on views/dashboard-my-parts.hbs
> +                                <div class="part-entry row" data-full={{name}}>
Ah that's probably the result of doing some manual testing. Not all of the data was present so I swapped out the variables with some hardcoded values to test that my changes were working correctly. Fixed it though, good catch!

2022-01-13 03:26 UTC, RogueArt commented on views/dashboard-my-parts.hbs
> +                    <hr class='banner-underline'>
Done, I've deleted it from the code completely.

2022-01-14 19:49 UTC, robertnperalta approved these changes
Just made a couple small changes to make things look better on phones. Thanks for all the hard work. LGTM!

2022-01-14 19:50 UTC, merged