Update Parts Checkout/Checkin to 2021 Design
ideahacks/ideahacks.la pull request #421
Opened 2021-11-11 21:40 UTC by TJ178

Page accessible after login at `admin/parts`

## Changes
- Change colorways of page, update some text prompts to match design
- Update some error prompts in the script for clarity
- Add media queries to improve responsiveness

## Concerns
- Doesn't match the Figma 100% bc of functionality differences, should be fine though.
- Button hover behavior was guessing on my part.
- The js is a mess, but it works
  - It would be nice to not have to redirect if there's an error, but that would involve some major scripting changes.

2021-12-18 00:16 UTC, robertnperalta requested changes
A couple more things I couldn't comment on the code:

* Change the `font-family` on the `form` element to Roboto to match the rest of the website
* Add an underline to the field where the user will have to scan the part to check it in/out. Right now with just the "SCAN A PART" filler, it's not clear that that's an input field
* A common frustration the last time this was in-person was that volunteers want to be able to scan the part before inputting the quantity. When using a barcode scanner, it inputs the scanned string along with a newline, so it auto-submits the form. Tweak the JS so they have to manually click the submit button or can press enter from the quantity field
* You can remove the `socket.io` link from the header. It hasn't been used in ages and just fills the console with errors on page load

2021-12-18 00:16 UTC, robertnperalta commented on views/admin-parts.hbs
> +            <h1>PARTS CHECKOUT</h1>
The header looks weird because you don't have the proper Google Fonts `link` in the page header and therefore don't have Source Code Pro available on the page. Add this to fix it:
```html
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;1,700;1,900&family=Source+Code+Pro:wght@400;500;700&display=swap" rel="stylesheet">
```
Also make sure to remove the old font `link`

2021-12-18 00:16 UTC, robertnperalta commented on public/css/admin-parts-checkout.css
>  }
For all the button styling, check out the "Log in" button on the login page. Generally the rule of thumb is that there shouldn't be any border and a white button on a black background should fade to white text on green.

2021-12-18 00:16 UTC, robertnperalta commented on public/css/admin-parts-checkout.css
> +	color: var(--green);
Change this to `var(--black)`. We never take input in a non-black color anywhere else on the website

2021-12-18 00:16 UTC, robertnperalta commented on public/css/admin-parts-checkout.css
> +	color: var(--green);
Same thing about text color here. This is being inherited by the quantity `input`, so make sure to override it to black for the `input`

2021-12-18 02:12 UTC, TJ178 commented on public/css/admin-parts-checkout.css
> +	color: var(--green);
Should the placeholder for "SCAN A PART" be black as well? 
![image](https://user-images.githubusercontent.com/22756691/146625639-7ac90c66-1612-4abe-a7d1-c996a100ac71.png)

2021-12-18 05:04 UTC, robertnperalta commented on public/css/admin-parts-checkout.css
> +	color: var(--green);
I think it's fine to leave as the translucent green. It needs some way of indicating it's not top-level text but a placeholder

2021-12-19 02:37 UTC, robertnperalta approved these changes
Added a quick commit so that all the input fields are cleared on error/success. Other than that LGTM!

2021-12-19 02:37 UTC, merged